DROP DATABASE IF EXISTS GitBot;
CREATE DATABASE GitBot;
USE GitBot;

DROP TABLE IF EXISTS Guild;
CREATE TABLE Guild (
	GuildID			VARCHAR(20) NOT NULL,
    DateAdded		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (GuildID)
);

DROP TABLE IF EXISTS Webhook;
CREATE TABLE Webhook (
	WebhookID		INT UNSIGNED NOT NULL AUTO_INCREMENT,
    GuildID			VARCHAR(20) NOT NULL,
    ChannelID		VARCHAR(20) NOT NULL,
    RepoURL			VARCHAR(200) NOT NULL,
    Secret			VARCHAR(40) NOT NULL,
    
    PRIMARY KEY (WebhookID),
    FOREIGN KEY (GuildID) REFERENCES Guild(GuildID)
);

SELECT * FROM Guild;
SELECT * FROM Webhook;