DROP DATABASE IF EXISTS GitBot;
CREATE DATABASE GitBot;
USE GitBot;

CREATE TABLE Webhook (
	WebhookID		INT UNSIGNED NOT NULL AUTO_INCREMENT,
    GuildID			INT UNSIGNED NOT NULL,
    ChannelID		INT UNSIGNED NOT NULL,
    RepoURL			VARCHAR(200) NOT NULL,
    Secret			VARCHAR(20) NOT NULL,
    
    PRIMARY KEY (WebhookID)
);